// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Payment struct {
	ID                uuid.UUID
	CheckoutRequestID string
	MerchantRequestID string
	PhoneNumber       string
	Amount            decimal.Decimal
	MpesaReceipt      string
	TransactionDate   time.Time
	ResultCode        int32
	ResultDesc        string
	CreatedAt         sql.NullTime
}
